version: '3'

services:
  manager:
    image: ecsdevops/aurora-manager:latest
    ports:
      - "3001:3001"
    networks:
      - frontend
    depends_on:
      - api
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  frontend: