export OS_REGION_NAME="de-fra1" # available: "nl-ams1" - "de-fra1" - "it-mil1"
export OS_AUTH_URL="https://api.${OS_REGION_NAME}.entercloudsuite.com/v2.0"
export OS_TENANT_NAME="<ECS_registration_email>"
export OS_PASSWORD="<ECS_registration_password>"
export OS_USERNAME="${OS_TENANT_NAME}"
